"""empty message

Revision ID: 36c9cd94a756
Revises: ab3fb01fedb0
Create Date: 2022-04-14 01:08:13.313981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36c9cd94a756'
down_revision = 'ab3fb01fedb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song_posts', sa.Column('genre', sa.Text(), nullable=False))
    op.add_column('song_posts', sa.Column('musician', sa.Text(), nullable=False))
    op.add_column('song_posts', sa.Column('releaseyear', sa.String(length=140), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song_posts', 'releaseyear')
    op.drop_column('song_posts', 'musician')
    op.drop_column('song_posts', 'genre')
    # ### end Alembic commands ###
